---
- hosts: minio
  gather_facts: false
  roles:
    - role: minio-init
      vars:
        minio_server_url: "{{ lookup('ansible.builtin.env', 'MINIO_SERVER_URL') }}"
        minio_access_key: "{{ lookup('ansible.builtin.env', 'MINIO_ACCESS_KEY') }}"
        minio_secret_key: "{{ lookup('ansible.builtin.env', 'MINIO_SECRET_KEY') }}"

        minio_buckets:
          - name: "test-bucket"
            state: present
            versioning: enable
            lifecycle_file: "files/custom-lifecycle-rules.json"

        minio_users:
          - name: "testuser"
            password: "testpass123"
            policies: ["readwrite"]
            state: present

        minio_policies:
          - name: "custom-readonly"
            policy_file: "files/custom-readonly-policy.json"
            state: present

        minio_access_keys:
          - name: "test-service-account"
            associated_user: "testuser"
            state: present
            secret_key: "testsecret123"
            expiry_duration: "1h"
            description: "Access key for testuser"
            policy_file: "files/custom-readonly-policy.json"
